- hosts: barq-servers
  become: yes
  serial: 1
  tasks:
    - name: Ensure log directory exists
      file:
        path: /var/log/barq
        state: directory
        mode: '0755'

    - name: Copy JAR file
      copy:
        src: ./barq-lite.jar
        dest: /opt/barq/barq-lite.jar
        mode: '0755'

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile.app
        dest: /opt/barq/Dockerfile.app

    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /opt/barq/docker-compose.yml

    - name: Build and run docker-compose
      shell: |
        cd /opt/barq
        docker compose down || true
        docker compose up -d --build
