- name: Ensure log directory exists
  file:
    path: /var/log/barq
    state: directory
    mode: '0755'

- name: Ensure SSL patrol directory exists
  file:
    path: /etc/ssl/patrol
    state: directory
    mode: '0755'

- name: Ensure reports directory exists
  file:
    path: /var/reports
    state: directory
    mode: '0755'

- name: Touch today's log file
  command: "touch /var/log/barq/barq-{{ ansible_date_time.date }}.log"
  args:
    creates: "/var/log/barq/barq-{{ ansible_date_time.date }}.log"
